# Generated by Django 3.2.6 on 2021-08-10 20:51

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', localflavor.us.models.USStateField(blank=True, max_length=2, null=True)),
                ('slope', models.FloatField(null=True)),
            ],
        ),
    ]
