# Generated by Django 3.2.6 on 2021-08-10 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('energy_app', '0002_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='intercept',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='Annual_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(max_length=4)),
                ('price', models.FloatField(null=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy_app.data')),
            ],
        ),
    ]
