# Generated by Django 3.2.6 on 2021-08-10 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_app', '0003_auto_20210810_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annual_data',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
